title: Ultimate Upsell & Cross Sell — Documentation
description: Complete guide for the Ultimate Upsell & Cross Sell Shopify app
#theme: just-the-docs
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

url: ""
baseurl: ""

# Navigation
nav_sort: case_insensitive

# Search
search_enabled: true

# Footer
footer_content: "Ultimate Upsell &amp; Cross Sell &copy; 2026"

# Collections
collections:
  docs:
    permalink: "/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: false
